server.port=8765

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

management.endpoints.web.exposure.include=*

jwt.secret-key=Q2hhdEdQVF9HeW5vX1NlY3JldF9LZXlfRm9yX1NwcmluZ19Cb290XzNfSmF2YTIxX01pY3Jvc2VydmljZXNfMjAyNg==

# Swagger Gateway

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.api-docs.enabled=true

# AUTH SERVICE
springdoc.swagger-ui.urls[0].name=Authentication Service
springdoc.swagger-ui.urls[0].url=/v3/api-docs/auth

# USER SERVICE
springdoc.swagger-ui.urls[1].name=User Service
springdoc.swagger-ui.urls[1].url=/v3/api-docs/users

# TRACKING SERVICE
springdoc.swagger-ui.urls[2].name=Tracking Service
springdoc.swagger-ui.urls[2].url=/v3/api-docs/tracking

# ANALYTICS SERVICE
spring.cloud.gateway.server.webmvc.routes[3].id=gyno-analytics-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://gyno-analytics-service
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/analytics/**