server.port=8765

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

management.endpoints.web.exposure.include=*

jwt.secret-key=Q2hhdEdQVF9HeW5vX1NlY3JldF9LZXlfRm9yX1NwcmluZ19Cb290XzNfSmF2YTIxX01pY3Jvc2VydmljZXNfMjAyNg==

# Swagger Gateway

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.api-docs.enabled=true

# AUTH SERVICE
springdoc.swagger-ui.urls[0].name=Authentication Service
springdoc.swagger-ui.urls[0].url=/v3/api-docs/auth

# USER SERVICE
springdoc.swagger-ui.urls[1].name=User Service
springdoc.swagger-ui.urls[1].url=/v3/api-docs/users

# TRACKING SERVICE
springdoc.swagger-ui.urls[2].name=Tracking Service
springdoc.swagger-ui.urls[2].url=/v3/api-docs/tracking

# ANALYTICS SERVICE
springdoc.swagger-ui.urls[3].name=Analytics Service
springdoc.swagger-ui.urls[3].url=/v3/api-docs/analytics

# NOTIFICATION SERVICE
springdoc.swagger-ui.urls[4].name=Notification Service
springdoc.swagger-ui.urls[4].url=/v3/api-docs/notification

# REPORT SERVICE
springdoc.swagger-ui.urls[5].name=Report Service
springdoc.swagger-ui.urls[5].url=/v3/api-docs/report