spring.application.name=gyno-notification-service
# SERVER
server.port=8085

# POSTGRESQL

spring.datasource.url=jdbc:postgresql://localhost:5432/gyno-notification-db
spring.datasource.username=postgres
spring.datasource.password=passer123

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# EUREKA

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# SMTP

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shewins.notifications@gmail.com
spring.mail.password=wdfrkqqiqovsnpry

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# KAFKA

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=latest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=true

spring.kafka.consumer.properties.spring.json.type.mapping=\
com.rokiasamake.analyticsservice.kafka.event.HealthInsightGeneratedEvent:com.rokiasamake.notificationservice.kafka.event.HealthInsightGeneratedEvent,\
com.rokiasamake.analyticsservice.kafka.event.PredictionGeneratedEvent:com.rokiasamake.notificationservice.kafka.event.PredictionGeneratedEvent