# SERVER
server.port=8084

# POSTGRESQL

spring.datasource.url=jdbc:postgresql://localhost:5432/gyno-analytics-db
spring.datasource.username=postgres
spring.datasource.password=passer123

spring.datasource.driver-class-name=org.postgresql.Driver

#JPA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# EUREKA

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# KAFKA

spring.kafka.bootstrap-servers=localhost:9092

# Producer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer

spring.kafka.consumer.group-id=analytics-group
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=true

spring.kafka.consumer.properties.spring.json.type.mapping=\
com.rokiasamake.trackingservice.kafka.event.EmotionCreatedEvent:com.rokiasamake.analyticsservice.kafka.event.EmotionCreatedEvent,\
com.rokiasamake.trackingservice.kafka.event.SymptomCreatedEvent:com.rokiasamake.analyticsservice.kafka.event.SymptomCreatedEvent,\
com.rokiasamake.trackingservice.kafka.event.FoodJournalCreatedEvent:com.rokiasamake.analyticsservice.kafka.event.FoodJournalCreatedEvent



